apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pylon.fullname" . }}-apps
  labels:
    {{- include "pylon.labels" . | nindent 4 }}
data:
  apps.json: |
    {{ .Values.apps | toJson | nindent 4 }}
