apiVersion: v1
kind: Service
metadata:
  name: {{ include "pylon.fullname" . }}
  labels:
    {{- include "pylon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "pylon.selectorLabels" . | nindent 4 }}
