apiVersion: v2
name: pylon
description: High-performance Pusher-compatible WebSocket server
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - websocket
  - pusher
  - realtime
home: https://github.com/oyro-os/pylon
maintainers:
  - name: pylon maintainers
